apiVersion: apps/v1
kind: Deployment
metadata:
  name: apoc-deployment
  labels:
    app: apoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apoc
  template:
    metadata:
      labels:
        app: apoc
    spec:
      containers:
      - name: apoc
        image: docker.pkg.github.com/atomicpocs/apoc/apoc:latest
        ports:
        - containerPort: 4567
      imagePullSecrets:
        - name: regcred
