name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
env:
  IMAGE: docker.pkg.github.com/atomicpocs/apoc/apoc
  IMAGE_VERSION: 1.1.O

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t $IMAGE:latest -t $IMAGE:$IMAGE_VERSION .

      - name: Push image
        run: docker push $IMAGE:latest && docker push $IMAGE:$IMAGE_VERSION
      
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBE_CONFIG }}
        id: setcontext
      
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/apoc-deployment.yaml
            k8s/apoc-service.yaml
            k8s/apoc-mapping.yaml
          images: |
            IMAGE_ID
          imagepullsecrets: |
            regcred
          namespace: atomic-pocs
